blank_issues_enabled: false
contact_links:
  - name: Telegram
    url: https://t.me/hyperledgeriroha
    about: Hyperledger Iroha Community channel is good place to ask the generic questions on Iroha.
  - name: Discord
    url: https://discord.gg/hyperledger
    about: There's also an Iroha channel on the Hyperledger Discord server.
